[package]
    edition = "2024"
    name = "stm32f1-freertos-example"
    version = "0.1.0"

[features]
    default = []
    i2c = []

[dependencies]
    cortex-m-rt = "0.7"
    defmt = "1"
    defmt-or-log = "0.2"
    defmt-rtt = "1"

    [dependencies.freertos-next]
        features = [
            "minimum",
            "critical-section-impl",
            "stack-high-water",
            "heap-free-size",
        ]
        version = "0.11"

    [dependencies.stm32f1-hal]
        features = ["f103", "x8", "defmt"]
        version = "0.13"

[build-dependencies]
    freertos-build = "0.5"

[profile.dev]
    codegen-units = 1
    debug = true
    # lto = true
    opt-level = 1
    panic = 'abort'
